site_name: Corey's WRIT 4999 Portfolio
theme:
  custom_dir: 'cinder-1.2.0'
site_author: Corey Wales
nav:
  - Home: 'docs/index.md'
  - Career Artifact: 'docs/microwave/career-based-artifact.md'
  - Capstone Project: 'docs/microwave/capstone-project-4999.md'
  - Writing Sample: 'docs/microwave/writing-sample.md'
  - Reflection: 'docs/microwave/reflection-summary.md'