site_name: Corey's WRIT 4999 Portfolio
theme:
  name: null
  custom_dir: cinder-1.2.0
site_author: Corey Wales
nav:
  - Home: index.md
  - Career Artifact: 'microwave/career-based-artifact.md'
  - Capstone Project: 'microwave/capstone-project-4999.md'
  - Writing Sample: 'microwave/writing-sample.md'
  - Reflection: 'microwave/reflection-summary.md'