site_name: Corey's WRIT 4999 Portfolio
theme:
  name: null
  custom_dir: 'cinder-1.2.0'
nav:
  - Home: docs/index.md
  - Career Artifact: docs/pages/career-based-artifact.md
  - Capstone Project: docs/pages/capstone-project-4999.md
  - Writing Sample: docs/pages/writing-sample.md
  - Reflection: docs/pages/reflection-summary.md